In [1]:
import numpy as np
from Network import Network

In [10]:
net = Network(3)

In [11]:
net.add_layer(4)

In [12]:
net.add_layer(1)

In [13]:
x = np.array([1, 2, 3])
len(x.shape)

1

In [14]:
net.predict(np.array([1, 2, 3]))

array([ 0.66856955])

In [7]:
np.insert(x, 1, 0)
x

array([1, 2, 3])

In [8]:
x = np.array([[1, 2, 3],[1, 2, 3],[1, 2, 3]])

In [9]:
x.T

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])